apiVersion: db2u.databases.ibm.com/v1
kind: Db2uInstance
metadata:
  name: {{ .Values.db2uInstance.name }}
  namespace: {{ .Values.namespace }}
spec:
  environment:
    authentication:
      ldap:
        enabled: false
    databases:
    - name: BLUDB
      storage:
      - name: data
        type: template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
          storageClassName: azuredisk-premium
      - name: activelogs
        type: template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          storageClassName: azuredisk-premium
    dbType: db2oltp
  license:
    accept: true
  nodes: 1
  podTemplate:
    db2u:
      resource:
        db2u:
          limits:
            cpu: "2"
            memory: "8Gi"
  storage:
  - name: meta
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 10Gi
      storageClassName: azurefile-nfs
    type: create
  - name: backup
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 10Gi
      storageClassName: azurefile-nfs
    type: create
  - name: archivelogs
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 10Gi
      storageClassName: azurefile-nfs
    type: create
  version: s11.5.9.0-cn1
