apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.loadBalancer.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: aks-db2-demo-eastus-001
    component: db2oltp
    formation_id: aks-db2-demo-eastus-001
    role: db
    type: engine
  externalTrafficPolicy: Local
  type: LoadBalancer
