apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  MYSQL_USER: bmJhZG1pbg==  # base64 encoded 'myuser'
  MYSQL_PASSWORD: K0xhcmF2YW4yMDEwCg==  # base64 encoded 'mypassword'
  MYSQL_DB: bmJhZG1pbgo=  # base64 encoded 'mydb'
