apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  mysql-user: bmJhZG1pbg==  # base64 encoded 'myuser'
  mysql-password: K0xhcmF2YW4yMDEw  # base64 encoded 'mypassword'
  mysql-db: bXNkYg==  # base64 encoded 'mydb'
