apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-backend
      version: v1
  template:
    metadata:
      labels:
        app: django-backend
        version: v1
    spec:
      containers:
      - name: django-backend
        image: vakem/nb-backend:latest  # Replace with your Docker image
        ports:
        - containerPort: 8000
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: mysql-db
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: mysql-user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: django-backend-service
spec:
  selector:
    app: django-backend
    version: v1
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP  # Change to LoadBalancer if needed
