apiVersion: apps/v1
kind: Deployment
metadata:
  name: members-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: members-frontend
  template:
    metadata:
      labels:
        app: members-frontend
    spec:
      containers:
      - name: members-frontend
        image: vakem/members-frontend:latest  # Replace with your Docker image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: members-frontend-service
spec:
  selector:
    app: members-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer  # Exposes Vue app externally
