#cloud-config
package_update: true
package_upgrade: true

packages:
  - openjdk-11-jdk
  - jenkins

runcmd:
  - sudo apt-get update -y
  - sudo apt-get install -y openjdk-11-jdk
  - sudo wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
  - echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
  - sudo apt-get update -y
  - sudo apt-get install -y jenkins
  - sudo systemctl enable jenkins
  - sudo systemctl start jenkins
  - sudo ufw allow 8080
  - sudo ufw allow OpenSSH
  - echo "Jenkins installation complete. Access Jenkins at http://<VM-Public-IP>:8080"
  - sudo ufw allow 22/tcp
  - sudo ufw allow 80/tcp
  - sudo ufw enable
