apiVersion: v1 
kind: Service 
metadata: 
  name: db2-lb 
  namespace: db2u 
spec: 
  ports: 
  - port: 50000 
    protocol: TCP 
    targetPort: 50000 
  selector: 
    app: aks-db2-demo-eastus-001 
    component: db2oltp 
    formation_id: aks-db2-demo-eastus-001 
    role: db 
    type: engine 
  externalTrafficPolicy: Local 
  type: LoadBalancer