# Create NFS file StorageClass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-nfs
allowVolumeExpansion: true
provisioner: file.csi.azure.com
parameters:
  protocol: nfs
  skuName: Premium_LRS