apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  SQL_USER: bmJhZG1pbg==  # base64 encoded 'myuser'
  SQL_PASSWORD: K0xhcmF2YW4yMDEw  # base64 encoded 'mypassword'
  SQL_DATABASE: bXNkYg==  # base64 encoded 'mydb'
