---
- hosts: localhost  #Testing the files once more
  connection: local
  collections:
    - azure.azcollection
  tasks:
    - name: Creating resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        state: present
        force_delete_nonempty: yes
        location: "{{ location }}"
