# db2u-subscription.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: db2u-operator-sub
  namespace: db2u
spec:
  channel: v2.0
  name: db2u-operator
  source: ibm-db2uoperator-catalog
  sourceNamespace: olm
  installPlanApproval: Automatic
