#cloud-config
package_update: true
package_upgrade: true

packages:
  - openjdk-17-jdk
  - jenkins
  
runcmd:
  - sudo apt update
  - sudo apt install -y openjdk-17-jre
  - wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
  - sudo sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'
  - sudo apt-get update
  - sudo ufw allow 8080
  - sudo ufw allow OpenSSH
  - sudo ufw allow 22/tcp
  - sudo ufw allow 443/tcp
  - sudo ufw allow 80/tcp
  - sudo ufw allow 8080/tcp
  - sudo apt-get install jenkins
  - sudo cat /var/lib/jenkins/secrets/initialAdminPassword
  - sudo systemctl enable jenkins
  - sudo ufw enable -y
 
  
