# mysql-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 2Gi  # Adjust as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql  # Local path for storage (adjust for your environment)
